[features]
seeds = false
skip-lint = false

[programs.localnet]
staking_pool = "8Dkwd74ntycfAMWKeudjELGroj5pqUpWk4MyLijuf1W7"
demo_faucet = "J12YAqC7dWbVWVAFveRdJ8SJ3sYc6roP3WJekhy4bDkM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"

[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.21"
