[package]
name = "staking_pool"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "staking_pool"

[dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"

[features]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
no-entrypoint = []

[lints]
workspace = true
